# Generated by Django 5.1.5 on 2025-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='avg_attitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professor',
            name='avg_clarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professor',
            name='avg_professionalism',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professor',
            name='feedback_count',
            field=models.IntegerField(default=0),
        ),
    ]
